import { Footer, Header, SocialStrip } from "../components/SiteChrome";

export default function EnglishHome() {
  return <><Header overlay locale="en" /><main>
    <section className="hero home-hero"><img className="hero-image" src="/images/home-main.jpg" alt="Torii Sushi - Japanese Restaurant Laval" /><div className="hero-shade" /><div className="hero-copy"><p className="script accent">The Ultimate</p><h1>JAPANESE EXPERIENCE IN LAVAL</h1><p className="script wine">Bring your own wine!</p><a className="primary-button" href="https://resy.com/cities/lvlq/restaurant-torii-sushi?date=2023-11-15&seats=2">Reservations</a></div></section>
    <section className="portal-intro"><p className="portal-title">TORII SUSHI IS A JAPANESE OASIS THAT SERVES AS A GATEWAY<br /> TO THE SACRED WORLD OF FINE DINING.</p><p className="portal-subtitle">CROSSING THE THRESHOLD OF OUR SUSHI RESTAURANT IS OPENING YOURSELF UP TO A SENSORY EXPERIENCE FIT FOR THE GODS!</p><p className="script owner">– Phat Nguyen, Owner</p></section>
    <section className="split-section story-section"><div className="split-image-wrap"><img src="/images/home-our-story.jpg" alt="Our Story" /></div><div className="split-copy"><p className="script accent eyebrow">Discover</p><h2>Our Story</h2><p className="caps">INSPIRED BY RICH JAPANESE CULTURE AND TRADITIONS</p><p>Torii Sushi invites you to experience a truly Japanese menu you won’t find anywhere else. Each bite, whether sushi, sashimi or maki, will stimulate your senses and tempt you into taking a trip…to Japan.</p></div></section>
    <section className="creations"><div className="section-heading"><h2>Creations</h2><h3>Torii Sushi</h3></div><div className="creation-grid">{["8292","8343","8479","8616"].map(id => <a className="creation-card" href="https://www.instagram.com/toriisushilaval/" key={id}><img src={`/images/photos/galerie-${id}.jpg`} alt="Torii Sushi creation" /><div className="creation-overlay"><h4>SEE OUR LATEST CREATIONS</h4><p>Discover our latest dishes on Instagram.</p></div></a>)}</div></section>
    <SocialStrip locale="en" />
    <section className="split-section restaurant-section"><div className="split-copy"><p className="script accent eyebrow">Our</p><h2>Restaurant</h2><p className="caps">TORII SUSHI, LOCATED IN THE HEART OF LAVAL FOR OVER 15 YEARS, IS A PERMANENT FIXTURE IN FINE JAPANESE DINING.</p><p>In addition to a wide variety of maki, sashimi and sushi, our chefs prepare a variety of Japanese food—from house creations to grilled platters and teriyaki. Whether a business lunch, family supper or get-together among friends, you will find exactly what you’re looking for.</p></div><div className="split-image-wrap"><img src="/images/our-restaurant.jpg" alt="Our restaurant" /></div></section>
    <section className="parallax-cta"><div><p className="script">An experience</p><h2>TO SAVOR</h2><a className="primary-button" href="https://resy.com/cities/lvlq/restaurant-torii-sushi?date=2023-11-15&seats=2">Reservations</a></div></section>
  </main><Footer locale="en" /></>;
}
